version: "3"
services:
  ocaml:
    build: .
    image: brainpower/ocaml-from-the-very-beginning-dev
    ports:
      - "8443:8443"
    environment:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - "./.git:/repo/.git"
      - "./chapters:/repo/chapters"
      - "./.gitignore:/repo/.gitignore"
      - "./dune-project:/repo/dune-project"
      - "./README.md:/repo/README.md"
      - "./docker-compose.yml:/repo/docker-compose.yml"
      - "./Dockerfile:/repo/Dockerfile"
      - "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK"
    working_dir: /repo
    command: code-server --allow-http --no-auth
